# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Temperature Monitoring and Control System

def classify_temperature(temp):
    if temp < 18:
        return "Cold"
    elif temp > 28:
        return "Hot"
    else:
        return "Normal"


def calculate_statistics(readings):
    average = sum(readings) / len(readings)
    highest = max(readings)
    lowest = min(readings)
    return average, highest, lowest


def display_report(avg, high, low, counts):
    print("\nTemperature Summary\n")
    print("Average Temperature =", round(avg, 2))
    print("Highest Temperature =", high)
    print("Lowest Temperature =", low)

    print("\nCondition Count")
    print("Hot =", counts["Hot"])
    print("Normal =", counts["Normal"])
    print("Cold =", counts["Cold"])

    print("\nSuggested Action")
    if counts["Hot"] > 0:
        print("Fan ON")
    if counts["Cold"] > 0:
        print("Heater ON")
    if counts["Hot"] == 0 and counts["Cold"] == 0:
        print("No action required")


# Main Program
def main():
    readings = []
    counts = {"Hot": 0, "Normal": 0, "Cold": 0}

    n = int(input("Enter number of readings: "))

    for i in range(n):
        temp = float(input("Enter temperature: "))
        readings.append(temp)

        condition = classify_temperature(temp)
        counts[condition] += 1

    avg, high, low = calculate_statistics(readings)
    display_report(avg, high, low, counts)


main()