# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import math

# Operation Functions
def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    if b == 0:
        return "Cannot divide by zero"
    return a / b

def power(a, b):
    return a ** b

def modulus(a, b):
    return a % b

def factorial(n):
    if n < 0:
        return "Factorial not defined for negative numbers"
    return math.factorial(n)

def square_root(n):
    if n < 0:
        return "Square root not defined for negative numbers"
    return math.sqrt(n)


# Main Program
def main():
    while True:
        print("\n------ Advanced Calculator ------")
        print("1 Addition")
        print("2 Subtraction")
        print("3 Multiplication")
        print("4 Division")
        print("5 Power")
        print("6 Modulus")
        print("7 Factorial")
        print("8 Square Root")
        print("9 Exit")

        try:
            choice = int(input("Enter choice: "))

            if choice == 9:
                print("Program terminated")
                break

            elif choice in [1, 2, 3, 4, 5, 6]:
                a = float(input("Enter first number: "))
                b = float(input("Enter second number: "))

                if choice == 1:
                    print("Result =", add(a, b))
                elif choice == 2:
                    print("Result =", subtract(a, b))
                elif choice == 3:
                    print("Result =", multiply(a, b))
                elif choice == 4:
                    print("Result =", divide(a, b))
                elif choice == 5:
                    print("Result =", power(a, b))
                elif choice == 6:
                    print("Result =", modulus(a, b))

            elif choice == 7:
                n = int(input("Enter number: "))
                print("Factorial =", factorial(n))

            elif choice == 8:
                n = float(input("Enter number: "))
                print("Square Root =", square_root(n))

            else:
                print("Invalid choice. Try again.")

        except ValueError:
            print("Invalid numeric input. Try again.")


main()